name: openapi deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  workflow_dispatch:

defaults:
  run: 
    working-directory: .

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test
    steps:

      # first checkout your code
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      
      - name: install & build
        run: |
          npm install -g redoc-cli
          redoc-cli bundle openapi.yaml -o docs/index.html
      
  deploy:
    needs: test_job
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
